### 哪些需要做异常处理

- JS语法错误、代码异常
- ajax请求异常
- 静态资源加载异常
- Promise异常
- Iframe异常
- 跨域Script error
- 崩溃和卡顿

### try-catch

`try-catch`只能捕获到同步运行时的错误，对语法和异步错误却无能为力，捕获不到(async/await除外)

1. 同步运行时错误

```javascript
 try {
  let name = 'wang';
  console.log(nam);
 } catch(e) {
   console.log('捕获到异常', e);
 }

// 输出：
// ReferenceError： nam is not defined
```
2. 不能捕获到语法错误（删除一个单引号）

```javascript
  try {
     let name = 'wang;
     console.log(nam);
  } catch(e) {
     console.log('捕获到异常', e);
  }

  // 输出：Uncaught SyntaxError: Invaild or unexpected token
```
3. 异步错误
```javascript
try {
   setTimeout(() => {
      undefined.map(v => v)
   }, 1000)
} catch(e) {
  console.log('捕获到异常：', e)
}
 // 输出： Uncaught TypeError: Cannot read property 'map' of undefined
```


> 思考：

JavaScript代码执行的过程：

- 第一阶段：JS代码从入口处开始执行，从头到尾执行同步代码，并将执行过程中产生的异步代码添加到事件队列中
- 第二阶段：同步代码执行完之后，通过事件循环机制检查事件队列执行此阶段产生的异步任务，每一个异步任务执行期间又看成了一个新的同步任务执行，如此循环
- `try-catch`是同步执行代码，在第一阶段的时候执行完毕，异步错误或者异常是在第二阶段执行的，同步代码不可能执行它的执行完以后的任务，所以捕获不到。
- 异步任务的执行是脱离当前主线程的

### Promise中异常的捕获

`promise`相比于`try-catch`更加容易捕获异步错误和异常。

> 注意点：

- 直接通过`return new Error('错误')`的方式返回异常不能被下一个`catch`捕获到，这里返回的`promise`是`resolve`的状态，会被`then`捕获到，只有`throw new Error()`才能被下一个`catch`捕获。

### React的异常捕获

- `componentDidCatch(error, info)`
- `static getDerivedStateFromError(error) ` React16.6

### window.onerror

当JS运行时错误发生时，`window`会触发一个`ErrorEvent`接口的`error`事件，并执行`window.onerror()`

```javascript
  window.onerror = function(message, source, lineno, colno, error) {
    // message: 错误信息(字符串)
    // source: 发生脚本的URL
    // lineno: 发生错误的行号(数字)
    // colno： 发生错误的列号(数字)
    // error: Error对象(对象)
    console.log('捕获到异常：', { message, source, lineo, colno, error});
  }
```

### window.addEventListener

```javascript
  window.addEventListener('error', (error) => {
     console.log('捕获到异常：', error);
  }, true)
```

参考：
[如何优雅处理前端异常](http://jartto.wang/2018/11/20/js-exception-handling/)
[JavaScript异常处理和思考](https://juejin.im/post/6844903857332436999)
[JavaScript异常处理](https://zhuanlan.zhihu.com/p/28131232)